# Generated by Django 4.2.9 on 2026-06-20 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxOfficeFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('sale', '售票'), ('refund', '退款'), ('fee', '手续费'), ('adjust', '调账')], max_length=16)),
                ('flow_no', models.CharField(max_length=64, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('ticket_amount', models.DecimalField(decimal_places=2, default=0, help_text='座位/套票原始金额', max_digits=12)),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('points_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, help_text='实收 = amount - 退款 - 手续费等前', max_digits=12)),
                ('payment_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('channel_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_received', models.DecimalField(decimal_places=2, default=0, help_text='实际到账净额', max_digits=12)),
                ('should_split_amount', models.DecimalField(decimal_places=2, default=0, help_text='应分账基数（扣除退款/手续费等）', max_digits=12)),
                ('is_settled', models.BooleanField(default=False)),
                ('biz_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'boxoffice_flows',
            },
        ),
        migrations.CreateModel(
            name='BoxOfficeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('show', '演出'), ('performance', '场次'), ('channel', '渠道'), ('daily', '按日'), ('period', '账期')], max_length=16)),
                ('dim_key', models.CharField(help_text='维度值：演出ID/场次ID/渠道ID/日期/账期编号', max_length=64)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_quantity', models.IntegerField(default=0)),
                ('total_ticket_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_coupon_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_points_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_payment_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_channel_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_refund', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_net_received', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_should_split', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('refund_count', models.IntegerField(default=0)),
                ('refund_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'boxoffice_summaries',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('default_commission_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'channels',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.CharField(default='', max_length=64)),
                ('start_at', models.DateTimeField()),
                ('total_seats', models.IntegerField(default=0)),
                ('sold_seats', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'performances',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_type', models.CharField(choices=[('flow_missing_split', '流水无分账'), ('split_missing_flow', '分账无流水'), ('amount_mismatch', '金额不匹配'), ('rounding_error', '四舍五入误差'), ('rollback_missing', '缺少回滚记录'), ('duplicate_split', '重复分账'), ('unknown', '未知差异')], default='unknown', max_length=32)),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('diff_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('description', models.TextField(blank=True, default='')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reconciliation_diffs',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recon_no', models.CharField(max_length=64, unique=True)),
                ('recon_type', models.CharField(choices=[('show', '演出对账'), ('performance', '场次对账'), ('daily', '按日对账'), ('period', '账期对账'), ('all', '全域对账')], default='all', max_length=16)),
                ('dim_key', models.CharField(blank=True, default='', max_length=64)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('total_net_received', models.DecimalField(decimal_places=2, default=0, help_text='票房实收合计', max_digits=14)),
                ('total_split_sum', models.DecimalField(decimal_places=2, default=0, help_text='各方分账净额之和', max_digits=14)),
                ('total_refund_sum', models.DecimalField(decimal_places=2, default=0, help_text='退款合计', max_digits=14)),
                ('total_fee_sum', models.DecimalField(decimal_places=2, default=0, help_text='手续费合计（支付+渠道）', max_digits=14)),
                ('total_coupon_points', models.DecimalField(decimal_places=2, default=0, help_text='优惠+积分抵扣承担合计', max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, default=0, help_text='差额 = 实收 - 分账 - 退款 - 手续费 - 承担', max_digits=14)),
                ('status', models.CharField(choices=[('pending', '待对账'), ('balanced', '平账'), ('unbalanced', '不平'), ('adjusted', '已调账')], default='pending', max_length=16)),
                ('diff_count', models.IntegerField(default=0)),
                ('remark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reconciliation_records',
            },
        ),
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_quantity', models.IntegerField(default=0)),
                ('refund_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.CharField(blank=True, default='', max_length=256)),
                ('operator', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'refund_records',
            },
        ),
        migrations.CreateModel(
            name='SettlementFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_no', models.CharField(max_length=64, unique=True)),
                ('flow_type', models.CharField(choices=[('payout', '我方打款给结算方'), ('receive', '结算方打款给我方'), ('adjust', '调账')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='CNY', max_length=8)),
                ('bank_transfer_no', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', '待确认'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=16)),
                ('operator', models.CharField(blank=True, default='', max_length=64)),
                ('remark', models.TextField(blank=True, default='')),
                ('transfer_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'settlement_flows',
            },
        ),
        migrations.CreateModel(
            name='SettlementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, default='', max_length=64)),
                ('performance_title', models.CharField(blank=True, default='', max_length=256)),
                ('performance_time', models.DateTimeField(blank=True, null=True)),
                ('split_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rollback_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('coupon_bear', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('points_bear', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_bear', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'settlement_items',
            },
        ),
        migrations.CreateModel(
            name='SettlementParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('party_type', models.CharField(choices=[('organizer', '主办方'), ('venue', '场地'), ('channel', '渠道'), ('platform', '平台'), ('tax', '税务'), ('other', '其他')], max_length=16)),
                ('contact', models.CharField(blank=True, default='', max_length=64)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('bank_account', models.CharField(blank=True, default='', max_length=64)),
                ('bank_name', models.CharField(blank=True, default='', max_length=128)),
                ('remark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'settlement_parties',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('troupe', models.CharField(blank=True, default='', max_length=128)),
                ('genre', models.CharField(choices=[('concert', '演唱会'), ('drama', '话剧'), ('musical', '音乐剧'), ('opera', '戏曲'), ('other', '其他')], default='concert', max_length=16)),
                ('status', models.CharField(choices=[('on_sale', '售票中'), ('upcoming', '待开票'), ('ended', '已结束')], default='upcoming', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shows',
            },
        ),
        migrations.CreateModel(
            name='SplitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('scope_type', models.CharField(choices=[('show', '演出'), ('performance', '场次')], default='show', max_length=16)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '生效'), ('inactive', '失效')], default='draft', max_length=16)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.06, help_text='税率，如6%则填0.06', max_digits=5)),
                ('tax_priority', models.IntegerField(default=1, help_text='税费扣除优先级，数字越小越先扣')),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_rules', to='tickets.performance')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_rules', to='tickets.show')),
            ],
            options={
                'db_table': 'split_rules',
            },
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=64)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('quantity', models.IntegerField(default=1)),
                ('original_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('points_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('channel_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('paid', '已支付'), ('refunded', '已退款'), ('partial_refunded', '部分退款'), ('cancelled', '已取消')], default='paid', max_length=16)),
                ('order_no', models.CharField(blank=True, default='', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tickets.channel')),
                ('coupon_bearer_party', models.ForeignKey(blank=True, help_text='优惠抵扣承担方', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_bearer_orders', to='tickets.settlementparty')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tickets.performance')),
                ('points_bearer_party', models.ForeignKey(blank=True, help_text='积分抵扣承担方', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_bearer_orders', to='tickets.settlementparty')),
            ],
            options={
                'db_table': 'ticket_orders',
            },
        ),
        migrations.CreateModel(
            name='SplitRuleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_type', models.CharField(choices=[('fixed', '固定金额'), ('rate', '比例抽成'), ('remaining', '剩余全部分配')], default='rate', max_length=16)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=4, default=0, help_text='比例，如50%则填0.50', max_digits=5)),
                ('priority', models.IntegerField(default=10, help_text='分配优先级，数字越小越先分配')),
                ('calc_base', models.CharField(choices=[('gross', '票房总额'), ('net_after_refund', '退款后净额'), ('net_after_tax', '税后净额'), ('remaining', '剩余可分配')], default='remaining', max_length=16)),
                ('coupon_bearer_type', models.CharField(choices=[('organizer', '主办方承担'), ('platform', '平台承担'), ('venue', '场地承担'), ('share', '按分账比例分摊')], default='platform', help_text='优惠抵扣承担方类型', max_length=16)),
                ('points_bearer_type', models.CharField(choices=[('organizer', '主办方承担'), ('platform', '平台承担'), ('venue', '场地承担'), ('share', '按分账比例分摊')], default='platform', help_text='积分抵扣承担方类型', max_length=16)),
                ('refund_bearer_type', models.CharField(choices=[('organizer', '主办方承担'), ('platform', '平台承担'), ('venue', '场地承担'), ('share', '按分账比例分摊')], default='share', help_text='退票损失承担方类型', max_length=16)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, default=0, help_text='0表示不限制', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_rule_items', to='tickets.settlementparty')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tickets.splitrule')),
            ],
            options={
                'db_table': 'split_rule_items',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SplitRollback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollback_reason', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollbacks', to='tickets.ticketorder')),
                ('original_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollback_original_flows', to='tickets.boxofficeflow')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollbacks', to='tickets.refundrecord')),
                ('rollback_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollback_flows', to='tickets.boxofficeflow')),
            ],
            options={
                'db_table': 'split_rollbacks',
            },
        ),
        migrations.CreateModel(
            name='SplitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, help_text='计算基数', max_digits=12)),
                ('split_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('split_amount', models.DecimalField(decimal_places=2, default=0, help_text='应分金额（正）', max_digits=12)),
                ('rollback_amount', models.DecimalField(decimal_places=2, default=0, help_text='已回滚金额（退票冲销）', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, help_text='净额 = split_amount - rollback_amount', max_digits=12)),
                ('coupon_bear', models.DecimalField(decimal_places=2, default=0, help_text='本方承担的优惠抵扣', max_digits=12)),
                ('points_bear', models.DecimalField(decimal_places=2, default=0, help_text='本方承担的积分抵扣', max_digits=12)),
                ('refund_bear', models.DecimalField(decimal_places=2, default=0, help_text='本方承担的退票损失', max_digits=12)),
                ('is_settled', models.BooleanField(default=False)),
                ('rollback_status', models.CharField(choices=[('normal', '正常'), ('rollback_partial', '部分回滚'), ('rollback_full', '全部回滚')], default='normal', max_length=16)),
                ('biz_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_details', to='tickets.boxofficeflow')),
                ('parent_split', models.ForeignKey(blank=True, help_text='冲销对应的原始分账明细', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollback_splits', to='tickets.splitdetail')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_details', to='tickets.settlementparty')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_details', to='tickets.splitrule')),
                ('rule_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_details', to='tickets.splitruleitem')),
            ],
            options={
                'db_table': 'split_details',
            },
        ),
        migrations.CreateModel(
            name='SettlementStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_no', models.CharField(max_length=64, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_split_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_rollback_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_coupon_bear', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_points_bear', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_refund_bear', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0, help_text='应付 = 应分 - 回滚 - 承担', max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, help_text='待付 = 应付 - 已付', max_digits=14)),
                ('status', models.CharField(choices=[('generated', '已生成'), ('confirmed', '已确认'), ('settled', '已结算'), ('rejected', '已驳回'), ('recalculated', '已重算')], default='generated', max_length=16)),
                ('remark', models.TextField(blank=True, default='')),
                ('confirmed_by', models.CharField(blank=True, default='', max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='tickets.settlementparty')),
                ('performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to='tickets.performance')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to='tickets.show')),
            ],
            options={
                'db_table': 'settlement_statements',
            },
        ),
        migrations.AddIndex(
            model_name='settlementparty',
            index=models.Index(fields=['party_type'], name='settlement__party_t_7348a3_idx'),
        ),
        migrations.AddField(
            model_name='settlementitem',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_items', to='tickets.boxofficeflow'),
        ),
        migrations.AddField(
            model_name='settlementitem',
            name='split_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_items', to='tickets.splitdetail'),
        ),
        migrations.AddField(
            model_name='settlementitem',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tickets.settlementstatement'),
        ),
        migrations.AddField(
            model_name='settlementflow',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_flows', to='tickets.settlementparty'),
        ),
        migrations.AddField(
            model_name='settlementflow',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_flows', to='tickets.settlementstatement'),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='tickets.ticketorder'),
        ),
        migrations.AddField(
            model_name='reconciliationrecord',
            name='performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recons', to='tickets.performance'),
        ),
        migrations.AddField(
            model_name='reconciliationrecord',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recons', to='tickets.show'),
        ),
        migrations.AddField(
            model_name='reconciliationdiff',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recon_diffs', to='tickets.boxofficeflow'),
        ),
        migrations.AddField(
            model_name='reconciliationdiff',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recon_diffs', to='tickets.ticketorder'),
        ),
        migrations.AddField(
            model_name='reconciliationdiff',
            name='recon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs', to='tickets.reconciliationrecord'),
        ),
        migrations.AddField(
            model_name='reconciliationdiff',
            name='split_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recon_diffs', to='tickets.splitdetail'),
        ),
        migrations.AddField(
            model_name='performance',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='tickets.show'),
        ),
        migrations.AddField(
            model_name='channel',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='tickets.settlementparty'),
        ),
        migrations.AddField(
            model_name='boxofficesummary',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxoffice_summaries', to='tickets.channel'),
        ),
        migrations.AddField(
            model_name='boxofficesummary',
            name='performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boxoffice_summaries', to='tickets.performance'),
        ),
        migrations.AddField(
            model_name='boxofficesummary',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boxoffice_summaries', to='tickets.show'),
        ),
        migrations.AddField(
            model_name='boxofficeflow',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxoffice_flows', to='tickets.channel'),
        ),
        migrations.AddField(
            model_name='boxofficeflow',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxoffice_flows', to='tickets.ticketorder'),
        ),
        migrations.AddField(
            model_name='boxofficeflow',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxoffice_flows', to='tickets.performance'),
        ),
        migrations.AddField(
            model_name='boxofficeflow',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxoffice_flows', to='tickets.refundrecord'),
        ),
        migrations.AddField(
            model_name='boxofficeflow',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxoffice_flows', to='tickets.show'),
        ),
        migrations.AddIndex(
            model_name='ticketorder',
            index=models.Index(fields=['performance', 'status'], name='ticket_orde_perform_dad944_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketorder',
            index=models.Index(fields=['channel'], name='ticket_orde_channel_594a75_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketorder',
            index=models.Index(fields=['created_at'], name='ticket_orde_created_17b07f_idx'),
        ),
        migrations.AddIndex(
            model_name='splitruleitem',
            index=models.Index(fields=['rule', 'priority'], name='split_rule__rule_id_e66d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='splitruleitem',
            index=models.Index(fields=['party'], name='split_rule__party_i_1ea41b_idx'),
        ),
        migrations.AddIndex(
            model_name='splitrule',
            index=models.Index(fields=['show', 'status'], name='split_rules_show_id_bd5e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='splitrule',
            index=models.Index(fields=['performance', 'status'], name='split_rules_perform_563c31_idx'),
        ),
        migrations.AddIndex(
            model_name='splitdetail',
            index=models.Index(fields=['flow'], name='split_detai_flow_id_240767_idx'),
        ),
        migrations.AddIndex(
            model_name='splitdetail',
            index=models.Index(fields=['party', 'biz_date'], name='split_detai_party_i_772d66_idx'),
        ),
        migrations.AddIndex(
            model_name='splitdetail',
            index=models.Index(fields=['rule'], name='split_detai_rule_id_c632a4_idx'),
        ),
        migrations.AddIndex(
            model_name='splitdetail',
            index=models.Index(fields=['is_settled'], name='split_detai_is_sett_3105a0_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementstatement',
            index=models.Index(fields=['party', 'period_start', 'period_end'], name='settlement__party_i_3dcdb6_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementstatement',
            index=models.Index(fields=['status'], name='settlement__status_f67d37_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementstatement',
            index=models.Index(fields=['statement_no'], name='settlement__stateme_ebc7ef_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementitem',
            index=models.Index(fields=['statement'], name='settlement__stateme_fcd6d3_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementitem',
            index=models.Index(fields=['split_detail'], name='settlement__split_d_a7cdc7_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementflow',
            index=models.Index(fields=['party', 'flow_type'], name='settlement__party_i_dfb4de_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementflow',
            index=models.Index(fields=['statement'], name='settlement__stateme_2fd695_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementflow',
            index=models.Index(fields=['status'], name='settlement__status_958fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrecord',
            index=models.Index(fields=['order'], name='refund_reco_order_i_9e0a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrecord',
            index=models.Index(fields=['created_at'], name='refund_reco_created_a2cae4_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['status'], name='reconciliat_status_74e31b_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['recon_type', 'dim_key'], name='reconciliat_recon_t_a3d1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationdiff',
            index=models.Index(fields=['recon', 'diff_type'], name='reconciliat_recon_i_5096eb_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationdiff',
            index=models.Index(fields=['is_resolved'], name='reconciliat_is_reso_95826e_idx'),
        ),
        migrations.AddIndex(
            model_name='boxofficesummary',
            index=models.Index(fields=['dimension', 'dim_key'], name='boxoffice_s_dimensi_14ffcd_idx'),
        ),
        migrations.AddIndex(
            model_name='boxofficesummary',
            index=models.Index(fields=['show'], name='boxoffice_s_show_id_b4a186_idx'),
        ),
        migrations.AddIndex(
            model_name='boxofficesummary',
            index=models.Index(fields=['performance'], name='boxoffice_s_perform_53481a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boxofficesummary',
            unique_together={('dimension', 'dim_key')},
        ),
        migrations.AddIndex(
            model_name='boxofficeflow',
            index=models.Index(fields=['performance', 'flow_type'], name='boxoffice_f_perform_b67528_idx'),
        ),
        migrations.AddIndex(
            model_name='boxofficeflow',
            index=models.Index(fields=['show', 'flow_type'], name='boxoffice_f_show_id_1d1552_idx'),
        ),
        migrations.AddIndex(
            model_name='boxofficeflow',
            index=models.Index(fields=['order'], name='boxoffice_f_order_i_646096_idx'),
        ),
        migrations.AddIndex(
            model_name='boxofficeflow',
            index=models.Index(fields=['created_at'], name='boxoffice_f_created_74c6ff_idx'),
        ),
    ]
